# Dockerfile Nginx
FROM nginx:1.24.0
RUN apt-get update && apt-get install -y \
    dnsutils \ 
    net-tools \
    iputils-ping \
    telnet \
    lsof
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf
RUN chmod 644 /etc/nginx/nginx.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
