version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge