version: '3.8'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile_nginx
    image: custom-nginx:1.24.0
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
