version: '3.8'

services:

  nginx:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile_nginx
    image: custom-nginx:1.24.0
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/nginx/resolv.conf:/etc/resolv.conf
    restart: unless-stopped
    extra_hosts:
      - "perfect-match:172.21.0.3"
    networks:
      webnet:
        ipv4_address: 172.21.0.3

  bind9:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile_bind9
    image: custom-bind9:9.18.12
    ports:
      - "8053:53/udp"
      - "8053:53/tcp"
    volumes:
      - ./backend/bind9/conf:/etc/bind
    networks:
      webnet:
        ipv4_address: 172.21.0.2

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
