# 
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y \
    bind9 \
    bind9utils \
    dnsutils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /etc/bind
COPY bind9/ /etc/bind/
COPY ../bind9/run.sh /run.sh
RUN chmod +x /run.sh
EXPOSE 53 53/udp
CMD ["/run.sh"]
